"""new table

Revision ID: 755d1a34ec59
Revises: 
Create Date: 2020-02-03 17:32:56.056246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755d1a34ec59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('s_n', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pin', sa.String(length=140), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('s_n'),
    sa.UniqueConstraint('pin')
    )
    op.create_index(op.f('ix_register_request_time'), 'register', ['request_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_request_time'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
