"""changed table name

Revision ID: f798380abe16
Revises: 2d0e8f916fb6
Create Date: 2020-01-31 11:59:10.807101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f798380abe16'
down_revision = '2d0e8f916fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_n', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=140), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('s_n')
    )
    op.create_index(op.f('ix_register_request_time'), 'register', ['request_time'], unique=False)
    op.drop_index('ix_Pin_request_time', table_name='Pin')
    op.drop_table('Pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('s_n', sa.INTEGER(), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=140), nullable=False),
    sa.Column('request_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('s_n')
    )
    op.create_index('ix_Pin_request_time', 'Pin', ['request_time'], unique=False)
    op.drop_index(op.f('ix_register_request_time'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
